### ISSUE TITLE
Step 5 - wrong number of implementing organizations stated

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#75]
In step 5 (set import preferences), the original set of implementing organisations is stated when I am importing **DFID** data, for the project **Climate Change Programme - Jolobayoo-O-Jibon**. It states 6 implementing organizations, but on step 3.2 there were only 2 (after determining the implementing organisations in step 3.1).

**Comment by tvldev02** [comment]
![image](https://cloud.githubusercontent.com/assets/17059642/16185438/aaefb83a-36e5-11e6-8578-46c13354c974.png)

Climate Change Programme - Jolobayoo-O-Jibon. It states 6 implementing organizations because the original IATI data has 6 implementing organizations. But the last two organizations are not mapped yet. So should we display only the mapped organizations count at step 5  (set import preferences)?

**Comment by markbrough** [comment]
Yes - let's only display the mapped organisations at step 5. Those are the only ones we want to import. If there were originally (e.g.) 2 implementing organisations but none of them are mapped, then the count should be 0. The user will then know that they should choose to manually enter the data into AIMS instead.
